[platformio]
default_envs = promicro
src_dir = Firmware

[env:promicro]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino
lib_deps = nicohood/HID-Project@^2.8.4
monitor_speed = 115200
